<?php

namespace App\Services\Notion;

use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use JsonException;
use RuntimeException;

/**
 * Stores and retrieves Atlas workspace maps.
 *
 * Maps come from two places:
 *   - Built-in, version-controlled maps in resources/data/ (the original
 *     conceptual atlas, plus any seeded real workspaces).
 *   - Runtime maps generated by crawls, written under storage/app/atlas.
 *
 * A runtime map shadows a built-in map with the same slug, so re-crawling a
 * seeded workspace simply replaces what is shown.
 */
class WorkspaceMapRepository
{
    private string $runtimeDir;

    public function __construct()
    {
        $this->runtimeDir = storage_path('app/atlas/workspaces');
    }

    /**
     * Summaries of every available map, newest-feeling first
     * (default map, then the rest alphabetically).
     *
     * @return array<int, array{slug: string, name: string, source: string, generatedAt: ?string, nodeCount: ?int}>
     */
    public function list(): array
    {
        $summaries = [];
        foreach ($this->slugs() as $slug) {
            $map = $this->load($slug);
            if ($map === null) {
                continue;
            }
            $meta = $map['meta'] ?? [];
            $summaries[$slug] = [
                'slug' => $slug,
                'name' => $meta['name'] ?? ($map['tree']['label'] ?? Str::headline($slug)),
                'source' => $meta['source'] ?? 'built-in',
                'generatedAt' => $meta['generatedAt'] ?? null,
                'nodeCount' => $meta['nodeCount'] ?? null,
            ];
        }

        uasort($summaries, function ($a, $b) {
            // Concept (public reference) first, then alphabetical.
            if ($a['slug'] === 'concept') {
                return -1;
            }
            if ($b['slug'] === 'concept') {
                return 1;
            }

            return strcasecmp($a['name'], $b['name']);
        });

        return array_values($summaries);
    }

    /**
     * Public default — the conceptual atlas shown at "/".
     */
    public function publicDefaultSlug(): string
    {
        $configured = (string) config('atlas.public_default', 'concept');

        if ($this->exists($configured) && $this->isPublic($configured)) {
            return $configured;
        }

        foreach ($this->slugs() as $slug) {
            if ($this->isPublic($slug)) {
                return $slug;
            }
        }

        return 'concept';
    }

    /**
     * Console default — the real workspace shown first in the backend.
     */
    public function consoleDefaultSlug(): string
    {
        $configured = (string) config('console.default_map', 'formosa-ev-hq');

        return $this->exists($configured) ? $configured : ($this->slugs()[0] ?? 'concept');
    }

    /**
     * A map is public only if it's the conceptual atlas or explicitly flagged
     * public. Crawled real workspaces are private and live behind the console.
     */
    public function isPublic(string $slug): bool
    {
        if ($slug === 'concept') {
            return true;
        }

        $map = $this->load($slug);
        if ($map === null) {
            return false;
        }

        return (bool) ($map['meta']['public'] ?? false);
    }

    /**
     * Summaries of public maps only (for the public-facing switcher).
     *
     * @return array<int, array{slug: string, name: string, source: string, generatedAt: ?string, nodeCount: ?int}>
     */
    public function publicList(): array
    {
        return array_values(array_filter(
            $this->list(),
            fn ($summary) => $this->isPublic($summary['slug'])
        ));
    }

    public function exists(string $slug): bool
    {
        return $this->pathFor($slug) !== null;
    }

    /**
     * @return array<string, mixed>|null
     */
    public function load(string $slug): ?array
    {
        $path = $this->pathFor($slug);
        if ($path === null) {
            return null;
        }

        try {
            return json_decode(File::get($path), true, 512, JSON_THROW_ON_ERROR);
        } catch (JsonException $e) {
            throw new RuntimeException("Map '{$slug}' is not valid JSON: ".$e->getMessage(), 0, $e);
        }
    }

    /**
     * Persist a crawled map as a runtime map and return its slug.
     *
     * @param  array<string, mixed>  $map
     */
    public function save(string $name, array $map): string
    {
        $slug = Str::slug($name) ?: 'workspace';

        if (! File::isDirectory($this->runtimeDir)) {
            File::makeDirectory($this->runtimeDir, 0755, true);
        }

        $map['meta'] = array_merge($map['meta'] ?? [], ['name' => $name, 'slug' => $slug]);

        File::put(
            $this->runtimeDir."/{$slug}.json",
            json_encode($map, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)
        );

        return $slug;
    }

    public function delete(string $slug): bool
    {
        $path = $this->runtimeDir."/{$slug}.json";
        if (File::exists($path)) {
            return File::delete($path);
        }

        return false;
    }

    /**
     * All known slugs (runtime shadowing built-in, plus the legacy concept map).
     *
     * @return array<int, string>
     */
    public function slugs(): array
    {
        $slugs = [];

        // Legacy/built-in conceptual atlas.
        if (File::exists(resource_path('data/atlas.json'))) {
            $slugs['concept'] = true;
        }

        foreach ($this->jsonFilesIn(resource_path('data/workspaces')) as $file) {
            $slugs[$file->getFilenameWithoutExtension()] = true;
        }

        foreach ($this->jsonFilesIn($this->runtimeDir) as $file) {
            $slugs[$file->getFilenameWithoutExtension()] = true;
        }

        return array_keys($slugs);
    }

    private function pathFor(string $slug): ?string
    {
        // Runtime maps take precedence over their built-in seed.
        $runtime = $this->runtimeDir."/{$slug}.json";
        if (File::exists($runtime)) {
            return $runtime;
        }

        $builtIn = resource_path("data/workspaces/{$slug}.json");
        if (File::exists($builtIn)) {
            return $builtIn;
        }

        if ($slug === 'concept' && File::exists(resource_path('data/atlas.json'))) {
            return resource_path('data/atlas.json');
        }

        return null;
    }

    /**
     * @return array<int, \SplFileInfo>
     */
    private function jsonFilesIn(string $dir): array
    {
        if (! File::isDirectory($dir)) {
            return [];
        }

        return collect(File::files($dir))
            ->filter(fn ($file) => strtolower($file->getExtension()) === 'json')
            ->values()
            ->all();
    }
}
